# Generated by Django 4.2 on 2023-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
